version: '3.8'
services:
  app:
    build:
      context: .
      target: production-main
      dockerfile: website/Dockerfile
    ports:
      - "3002:3000"
    env_file:
      - website/.env
    depends_on:
      - websocket

  websocket:
    build:
      context: .
      target: production-websocket
      dockerfile: website/Dockerfile
    ports:
      - "8081:8080"
    env_file:
      - website/.env

  sharp:
    build:
      context: .
      dockerfile: SHARP/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    env_file:
      - SHARP/.env

volumes:
  sharp_pgdata: