version: '3.8'
services:
  app:
    build:
      context: .
      target: production-main
      dockerfile: website/Dockerfile
    ports:
      - "3002:3000"
    volumes:
      - ./website:/app
      - website_node_modules:/app/node_modules
    env_file:
      - website/.env
    depends_on:
      - websocket

  websocket:
    build:
      context: .
      target: production-websocket
      dockerfile: website/Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - ./websocket:/app
      - websocket_node_modules:/app/node_modules
    env_file:
      - website/.env

volumes:
  website_node_modules:
  websocket_node_modules:
