services:
  app:
    build:
      context: .
      target: production-main
      dockerfile: website/Dockerfile
    ports:
      - "3002:3000"
    env_file:
      - .env
    depends_on:
      - websocket

  websocket:
    build:
      context: .
      target: production-websocket
      dockerfile: website/Dockerfile
    ports:
      - "8081:8080"
    env_file:
      - .env